### ISSUE TITLE
You need to add a HUGE WARNING of the cost involved!

### ISSUE THREAD

**Issue by hastarin** [Azure-Samples/iot-hub-c-huzzah-getstartedkit#10]
I just got a bill for over AUD$1700 for a month.   I'd shut things down as mentioned in the tutorial but hadn't deleted them.

For an individual hobbyist/maker this is obviously the wrong platform and getting a bill like this is just ridiculous!

**Comment by hegate** [comment]
Hi @hastarin , I'm sorry you had such experience. The first tutorial is heavy on resources consumption and we will definitely reinforce the message on the tutorial so it's clearer. This is mostly as a result of the simulated devices sending data constantly to the solution, not the price of the different services per se. We believe our platform offers a good solution for hobbyist/makers, but the second tutorial is more suitable for a long running solution that's more resources sensitive. We will update the tutorial to make it more explicit. Is there any email that we can use to reach out to you and keep the conversation?

**Comment by hastarin** [comment]
@hegate Thankfully the charge was refunded.  I would have sworn I shut down everything, including disabling the simulated devices.  I've since deleted everything to avoid any further charges.

My email is my github username at gmail.com

**Comment by hegate** [comment]
Thanks @hastarin , we definitely hate when makers and hobbyist have a bad experience using Azure IoT. I'll reach out to you on email as well. Thanks for trying out our technology!
