### ISSUE TITLE
Can't find sdk/schemaserializer

### ISSUE THREAD

**Issue by SQLScott** [Azure-Samples/iot-hub-c-huzzah-getstartedkit#13]
I have downloaded the code and am trying to compile it, but I am getting the error "fatal error: sdk/schemaserializer.h: no such file or directory exists". What am I missing? Is there a library that I need to install first?

**Comment by mamokarz** [comment]
Hi SQLScott,

schemaserialier is part of the Azure IoT SDK. For the Arduino, you can download it from https://github.com/arduino-libraries/AzureIoTHub or install it directly from the Arduino IDE; just look for AzureIoTHub in the Sketch->Include Library->Manage Libraries.

**Comment by mamokarz** [comment]
We've just moved https://github.com/arduino-libraries/AzureIoTHub to https://github.com/Azure/azure-iot-arduino

**Comment by Ilias-Tsigkogiannis** [comment]
Closing this issue, as the problem should be fixed by adding the AzureIoTHub library by going to Sketch -> Include Library -> Manage Libraries -> AzureIoTHub
