### ISSUE TITLE
Remote Monitoring sample breaks on Olimex ESP8266

### ISSUE THREAD

**Issue by Peter-B-** [Azure-Samples/iot-hub-c-huzzah-getstartedkit#7]
Hello

I tried to get this sample running on an Olimex ESP8266, but it crashes at line 251 of remote_monitoring.c:
`IoTHubClient_LL_DoWork(iotHubClientHandle);`

On the serial port it outputs
`Fatal exception 29(StoreProhibitedCause):
epc1=0x4000e1b2, epc2=0x00000000, epc3=0x00000000, excvaddr=0x00000004, depc=0x0000`
 before restarting the program.

Does anyone have any idea what is happening here? Will it not run on my board?

Greetings
Peter

**Comment by AttunixCorp** [comment]
Hi Peter,

The Olimex ESP8266 is not supported at this time. I would recommend trying the nightly build of the Arduino IDE and ensure you are updating the ESP8266 library: Visiting https://github.com/esp8266/Arduino and following the instructions for “Using git version” using Python 2.7.x
